name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Please ensure that all issues include what is happening and what is expected instead.'
        pr-message: 'New pull requests will be reviewed by the repo owners and must include an issue number in the pull request'
